version: 2
jobs:

  Deploy:
    docker:
      - image: circleci/ruby:2.7.1
    working_directory: ~/NKCUG_Slack_Bot

    steps:
      - run:
          name: Escape Japanese characters
          command: 'git config --global core.quotepath false'

      - checkout

      - add_ssh_keys

      - run:  
          name: Start ssh-keyscan  
          command: |  
            ssh-keyscan -p ${SSH_PORT} ${HOST_NAME} >> ~/.ssh/known_hosts 
            
      - run:
          name: stopping application container
          command: ssh -p ${SSH_PORT} ${USER_NAME}@${HOST_NAME} "cd ${PROJECT_DIRECTORY} && docker-compose down"

      - run:
          name: update server's local master
          command: ssh -p ${SSH_PORT} ${USER_NAME}@${HOST_NAME} "cd ${PROJECT_DIRECTORY} && git pull origin master"

      - run:
          name: restart container
          command: ssh -p ${SSH_PORT} ${USER_NAME}@${HOST_NAME} "cd ${PROJECT_DIRECTORY} && docker-compose up -d"
workflows:
  version: 2
  Lintcheck_And_Build:
    jobs:
      - Deploy:
          # runnning only updating master branch
          filters:
            branches:
              only: master